name: Stage the app

on: 
  pull_request:
    types: [labeled]
    
env:
  DOCKER_IMAGE_NAME: pkal42-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: pkal42-ttt-app


jobs:
  build:
    runs-on: ubuntu-latest
